test_csv: "D:/Codes/LineArtPred/data/csv/test4_有先验有跑图方便快速对比.csv"
image_dir: "D:/Codes/JigsawPrediction/data/test4_images"

batch_size: 32
use_gpu: true
num_classes: 5

checkpoints:
  - "models/coca_vit_b_32/checkpoints/best_model_epoch_3.pth"
  - "models/coca_vit_b_32/checkpoints1/best_model_epoch_1.pth"
  - "models/coca_vit_b_32/checkpoints2/best_model_epoch_1.pth"

use_features:
  use_full_image: true
  use_numeric_features: true
  use_text_hierarchy: true
